const collegeAndUniversity = {
    AK : [
        {name : 'University of Alaska' , website : 'http://alaska.edu' , state : 'Ak'},
        {name : 'Alaska Christian College' , website : 'http://alaskacc.edu' , state : 'Ak'},
        {name : 'National Park Community College' , website : 'http://npcc.edu' , state : 'Ak'},
        {name : 'University of Alaska Fairbanks' , website : 'http://uaf.edu' , state : 'Ak'},
        {name : 'University of Arkansas – Fort Smith' , website : 'http://uafs.edu' , state : 'Ak'},
    ],
    AL : [
        {name : 'Alabama A&M University' , website : 'http://aamu.edu' , state : 'AL'},
        {name : 'Athens State University' , website : 'http://athens.edu' , state : 'AL'},
        {name : 'Auburn University' , website : 'http://auburn.edu' , state : 'AL'},
        {name : 'Auburn University at Montgomery' , website : 'http://aum.edu' , state : 'AL'},
        {name : 'Birmingham-Southern College' , website : 'http://bsc.edu' , state : 'AL'},
        {name : 'Calhoun Community College' , website : 'http://calhoun.edu' , state : 'AL'},
        {name : 'Enterprise State Community College' , website : 'http://escc.edu' , state : 'AL'},
        {name : 'Faulkner State Community College' , website : 'http://faulknerstate.edu' , state : 'AL'},
        {name : 'Gadsden State  Community College' , website : 'http://gadsdenstate.edu' , state : 'AL'},
        {name : 'Huntingdon College' , website : 'http://huntingdon.edu' , state : 'AL'},
        {name : 'Jacksonville State University' , website : 'http://jsu.edu' , state : 'AL'},
        {name : 'Lurleen B. Wallace Community College' , website : 'http://lbwcc.edu' , state : 'AL'},
        {name : 'University of Montevallo' , website : 'http://montevallo.edu' , state : 'AL'},
        {name : 'Northeast Alabama Community College' , website : 'http://nacc.edu' , state : 'AL'},
        {name : 'Northwest-Shoals Community College' , website : 'http://nwscc.edu' , state : 'AL'},
        {name : 'Oakwood University' , website : 'http://oakwood.edu' , state : 'AL'},
        {name : 'Samford University' , website : 'http://samford.edu' , state : 'AL'},
        {name : 'Southeastern Bible College' , website : 'http://sebc.edu' , state : 'AL'},
        {name : 'University of South Alabama' , website : 'http://southalabama.edu' , state : 'AL'},
        {name : 'Trenholm State Technical College' , website : 'http://trenholmstate.edu' , state : 'AL'},
        {name : 'Troy University' , website : 'http://troy.edu' , state : 'AL'},
        {name : 'Tuskegee University' , website : 'http://tuskegee.edu' , state : 'AL'},
        {name : 'University of Alabama' , website : 'http://ua.edu' , state : 'AL'},
        {name : 'University of Alabama at Birmingham' , website : 'http://uab.edu' , state : 'AL'},
        {name : 'University of Alabama in Huntsville' , website : 'http://uah.edu' , state : 'AL'},
        {name : 'University of North Alabama' , website : 'http://una.edu' , state : 'AL'},
        {name : 'Snead State Community College' , website : 'http://snead.edu' , state : 'AL'},
    ],
    AR : [
        {name : 'Arkansas Northeastern College' , website : 'http://anc.edu' , state : 'AR'},
        {name : 'Arkansas State University' , website : 'http://astate.edu' , state : 'AR'},
        {name : 'Arkansas Tech University' , website : 'http://atu.edu' , state : 'AR'},
        {name : 'Central Baptist College' , website : 'http://cbc.edu' , state : 'AR'},
        {name : 'Harding University' , website : 'http://harding.edu' , state : 'AR'},
        {name : 'Hendrix College' , website : 'http://hendrix.edu' , state : 'AR'},
        {name : 'Henderson State University' , website : 'http://hsu.edu' , state : 'AR'},
        {name : 'John Brown University' , website : 'http://jbu.edu' , state : 'AR'},
        {name : 'Lyon College	' , website : 'http://lyon.edu' , state : 'AR'},
        {name : 'Mid-South Community College' , website : 'http://midsouthcc.edu' , state : 'AR'},
        {name : 'North Arkansas College' , website : 'http://northark.edu' , state : 'AR'},
        {name : 'Northwest Arkansas Community College' , website : 'http://nwacc.edu' , state : 'AR'},
        {name : 'Northwest Technical Institute' , website : 'http://nwti.edu' , state : 'AR'},
        {name : 'Ouachita Baptist University' , website : 'http://obu.edu' , state : 'AR'},
        {name : 'University of the Ozarks' , website : 'http://ozarks.edu' , state : 'AR'},
        {name : 'Phillips Community College U of A' , website : 'http://pccua.edu' , state : 'AR'},
        {name : 'Pulaski Technical College' , website : 'http://pulaskitech.edu' , state : 'AR'},
        {name : 'Southern Arkansas University Magnolia' , website : 'http://saumag.edu' , state : 'AR'},
        {name : 'Southeast Arkansas College' , website : 'http://seark.edu' , state : 'AR'},
        {name : 'University of Arkansas Community College Batesville' , website : 'http://uaccb.edu' , state : 'AR'},
        {name : 'University of Arkansas at Little Rock' , website : 'http://ualr.edu' , state : 'AR'},
        {name : 'University of Arkansas for Medical Sciences' , website : 'http://uams.edu' , state : 'AR'},
        {name : 'University of Arkansas at Pine Bluff' , website : 'http://uapb.edu' , state : 'AR'},
        {name : 'University of Arkansas' , website : 'http://uark.edu	' , state : 'AR'},
        {name : 'University of Central Arkansas' , website : 'http://uca.edu' , state : 'AR'},
        {name : 'Williams Baptist College' , website : 'http://wbcoll.edu' , state : 'AR'},
    ],
    AZ : [
        {name : 'University of Arizona' , website : 'http://arizona.edu' , state : 'AZ'}, 
        {name : 'Arizona State University' , website : 'http://asu.edu' , state : 'AZ'}, 
        {name : 'Arizona Western College' , website : 'http://azwestern.edu' , state : 'AZ'}, 
        {name : 'Bryan University' , website : 'http://bryanuniversity.edu' , state : 'AZ'}, 
        {name : 'Central Arizona College' , website : 'http://centralaz.edu' , state : 'AZ'}, 
        {name : 'Glendale Community College' , website : 'http://gccaz.edu' , state : 'AZ'}, 
        {name : 'Grand Canyon University' , website : 'http://gcu.edu' , state : 'AZ'}, 
        {name : 'Maricopa Community Colleges' , website : 'http://maricopa.edu' , state : 'AZ'}, 
        {name : 'Mesa Community College' , website : 'http://mesacc.edu' , state : 'AZ'}, 
        {name : 'Northern Arizona University' , website : 'http://nau.edu' , state : 'AZ'}, 
        {name : 'Northland Pioneer  College' , website : 'http://npc.edu' , state : 'AZ'}, 
        {name : 'University of Phoenix' , website : 'http://phoenix.edu' , state : 'AZ'}, 
        {name : 'Phoenix College' , website : 'http://phoenixcollege.edu' , state : 'AZ'}, 
        {name : 'Pima Community College' , website : 'http://pima.edu' , state : 'AZ'}, 
        {name : 'Prescott College' , website : 'http://prescott.edu' , state : 'AZ'}, 
        {name : 'Rio Salado College' , website : 'http://riosalado.edu' , state : 'AZ'}, 
        {name : 'South Mountain Community College' , website : 'http://southmountaincc.edu' , state : 'AZ'}, 
        {name : 'University of Advancing Technology' , website : 'http://uat.edu' , state : 'AZ'}, 
        {name : 'Yavapai College' , website : '	http://yc.edu' , state : 'AZ'}, 
    ],
    CA : [
        {name : 'Academy of Arts University' , website : 'http://academyart.edu' , state : 'CA'}, 
        {name : 'Adance Computing Institute' , website : 'http://advancedcomputinginstitute.edu' , state : 'CA'}, 
        {name : 'Acupuncture & Integrative Medicine College' , website : 'http://aimc.edu' , state : 'CA'}, 
        {name : 'Alliant International University' , website : 'http://alliant.edu' , state : 'CA'}, 
        {name : 'Allied American University' , website : 'http://allied.edu' , state : 'CA'}, 
        {name : 'Anaheim University' , website : 'http://anaheim.edu' , state : 'CA'}, 
        {name : 'Academy of Arts University' , website : 'http://academyart.edu' , state : 'CA'}, 
        {name : 'Academy of Arts University' , website : 'http://academyart.edu' , state : 'CA'}, 
        {name : 'Academy of Arts University' , website : 'http://academyart.edu' , state : 'CA'}, 
        {name : 'Academy of Arts University' , website : 'http://academyart.edu' , state : 'CA'}, 
        {name : 'Academy of Arts University' , website : 'http://academyart.edu' , state : 'CA'}, 
        {name : 'Academy of Arts University' , website : 'http://academyart.edu' , state : 'CA'}, 
        {name : 'Academy of Arts University' , website : 'http://academyart.edu' , state : 'CA'}, 
        {name : 'Academy of Arts University' , website : 'http://academyart.edu' , state : 'CA'}, 
    ]
};

// Angeles College	http://angelescollege.edu	CA
// Antioch University Los Angeles	http://antiochla.edu	CA
// Argosy University	http://argosy.edu	CA
// Art Center College of Design	http://artcenter.edu	CA
// The Art Institute	http://artinstitutes.edu	CA
// Ashford University	http://ashford.edu	CA
// ATI College	http://ati.edu	CA
// Antelope Valley College	http://avc.edu	CA
// Bakersfield College	http://bakersfieldcollege.edu	CA
// Barstow Community College	http://barstow.edu	CA
// Berkeley University of California	http://berkeley.edu	CA
// Berkeley City College	http://berkeleycitycollege.edu	CA
// Brandman University	http://brandman.edu	CA
// Butte College	http://butte.edu	CA
// Cabrillo College	http://cabrillo.edu	CA
// California Institute of the Arts	http://calarts.edu	CA
// California Baptist University	http://calbaptist.edu	CA
// California Lutheran University	http://callutheran.edu	CA
// California Miramar University	http://calmu.edu	CA
// California Polytechnic State University	http://calpoly.edu	CA
// California State University	http://calstate.edu	CA
// California Institute of Technology	http://caltech.edu	CA
// Canada College	http://canadacollege.edu	CA
// College of the Canyons	http://canyons.edu	CA
// California College of the Arts	http://cca.edu	CA
// California Community Colleges Chanellor’s Office	http://cccco.edu	CA
// City College of San Francisco	http://ccsf.edu	CA
// Cerritos College	http://cerritos.edu	CA



